# Generated by Django 4.2.16 on 2024-11-17 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('especialidad', models.CharField(choices=[('Justicia', 'Justicia'), ('Sanidad', 'Sanidad'), ('Educación', 'Educacion'), ('Fuerzas y cuerpos de seguridad', 'Seguridad'), ('Administración General', 'Admin General'), ('Técnicas y Especialidad', 'Tecnicas'), ('Servicios Sociales', 'Serv Sociales'), ('Culturales', 'Culturales'), ('Correos', 'Correos'), ('Economía y Estadística', 'Economia')], max_length=50)),
                ('modalidad', models.CharField(choices=[('Híbrido', 'Hibrido'), ('On-Line', 'Online'), ('Presencial', 'Presencial')], max_length=20)),
                ('fecha_inicio', models.DateField()),
                ('fecha_finalizacion', models.DateField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vacantes', models.PositiveIntegerField(default=0, verbose_name='Vacantes disponibles')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miércoles', 'Miercoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes'), ('Sábado', 'Sabado'), ('Domingo', 'Domingo')], max_length=10)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='Administrador.curso')),
            ],
            options={
                'verbose_name': 'Horario',
                'verbose_name_plural': 'Horarios',
            },
        ),
        migrations.AddConstraint(
            model_name='horario',
            constraint=models.UniqueConstraint(fields=('curso', 'dia', 'hora_inicio', 'hora_fin'), name='unique_horario'),
        ),
    ]
