# Generated by Django 4.2.16 on 2024-11-29 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrador', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='gastos_gestion',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=6, verbose_name='Gastos de gestión'),
        ),
        migrations.AddField(
            model_name='curso',
            name='horas_semanales',
            field=models.PositiveIntegerField(default=0, verbose_name='Horas por semana'),
        ),
    ]
