# Generated by Django 4.2.16 on 2024-11-29 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrador', '0002_curso_gastos_gestion_curso_horas_semanales'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='horas_semanales',
        ),
        migrations.AlterField(
            model_name='curso',
            name='gastos_gestion',
            field=models.DecimalField(decimal_places=2, default=8.99, max_digits=6, verbose_name='Gastos de gestión'),
        ),
    ]
