# Generated by Django 4.2.16 on 2024-11-29 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrador', '0003_remove_curso_horas_semanales_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='gastos_gestion',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=6, verbose_name='Gastos de gestión'),
        ),
    ]
