# Generated by Django 4.2.16 on 2024-11-29 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Administrador', '0004_alter_curso_gastos_gestion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='gastos_gestion',
        ),
    ]
