# Generated by Django 4.2.16 on 2024-12-02 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrador', '0005_remove_curso_gastos_gestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/', verbose_name='Imagen del Curso'),
        ),
    ]
