# Generated by Django 4.2.16 on 2024-12-02 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrador', '0006_curso_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes_cursos', verbose_name='Imagen del Curso'),
        ),
    ]
