# Generated by Django 4.2.16 on 2024-11-25 18:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Administrador', '0001_initial'),
        ('Gestion_Cursos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recibo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateTimeField()),
                ('importe', models.DecimalField(decimal_places=2, max_digits=8)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recibos', to='Administrador.curso')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recibos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
