# Generated by Django 4.2.16 on 2024-11-25 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_Cursos', '0002_recibo'),
    ]

    operations = [
        migrations.AddField(
            model_name='recibo',
            name='metodo_pago',
            field=models.CharField(default='Tarjeta', max_length=50),
            preserve_default=False,
        ),
    ]
