# Generated by Django 4.2.16 on 2024-11-29 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_Cursos', '0003_recibo_metodo_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='recibo',
            name='estado',
            field=models.CharField(choices=[('Pagado', 'Pagado'), ('No Pagado', 'No Pagado')], default='No\xa0Pagado', max_length=10),
        ),
    ]
