# Generated by Django 4.2.16 on 2024-11-29 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_Cursos', '0004_recibo_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recibo',
            name='estado',
            field=models.CharField(choices=[('Pagado', 'Pagado'), ('No Pagado', 'No Pagado')], default='No Pagado', max_length=10),
        ),
    ]
