# Generated by Django 4.2.16 on 2024-12-04 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_Cursos', '0005_alter_recibo_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='recibo',
            name='codigo_referencia',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
