# Generated by Django 4.2.16 on 2024-12-04 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Administrador', '0007_alter_curso_imagen'),
        ('Gestion_Cursos', '0006_recibo_codigo_referencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReciboNoAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('fecha_pago', models.DateTimeField()),
                ('importe', models.DecimalField(decimal_places=2, max_digits=8)),
                ('metodo_pago', models.CharField(max_length=50)),
                ('estado', models.CharField(choices=[('Pagado', 'Pagado'), ('No Pagado', 'No Pagado')], default='No Pagado', max_length=10)),
                ('codigo_referencia', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recibos_noauth', to='Administrador.curso')),
            ],
        ),
        migrations.CreateModel(
            name='CarritoNoAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('fecha_agregado', models.DateTimeField(auto_now_add=True)),
                ('nombre', models.CharField(max_length=255)),
                ('email_usuario', models.EmailField(max_length=254)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administrador.curso')),
            ],
        ),
    ]
