# Generated by Django 4.2.16 on 2024-12-04 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_Cursos', '0007_recibonoauth_carritonoauth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carritonoauth',
            name='email_usuario',
        ),
        migrations.RemoveField(
            model_name='carritonoauth',
            name='nombre',
        ),
    ]
